## ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # evita lanzar hyprlock dos veces
    before_sleep_cmd = loginctl lock-session     # bloquea justo antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on    # reactiva pantalla al despertar
}

# Atenuar brillo a los 2.5 min de inactividad
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Bloquear pantalla a los 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar el monitor a los 5.5 min (justo después de bloquear)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspender el equipo a los 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
